User's Guide
------------

This part of the documentation will show you how to get started in using
Flask-SQLAlchemy with Flask.

.. toctree::
   :maxdepth: 2

   quickstart
   contexts
   config
   models
   queries
   binds
   signals
   customizing

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Requirements
............

OS support: Linux, Windows, MacOS

Python support:

.. csv-table::
   :header: "Our Version", "Python", "Flask", "SQLAlchemy"

   "2.x", "2.7, 3.4+", 0.12+, "0.8+ or 1.0.10+ w/ Python 3.7"
   "3.0+ (in dev)", "2.7, 3.5+", 1.0+, 1.0+

If doubts arise, you can always check to see what we are testing:

* `2.x: tox.ini <https://github.com/pallets/flask-sqlalchemy/blob/2.x-maintenance/tox.ini>`_
* `dev: tox.ini <https://github.com/pallets/flask-sqlalchemy/blob/master/tox.ini>`_
* We only run CI for Linux currently (`#690 <https://github.com/pallets/flask-sqlalchemy/issues/690>`_)



License
.......

See `our license <https://github.com/pallets/flask-sqlalchemy/blob/master/LICENSE>`_ for legal
information governing this project.


Changelog
.........

.. toctree::
   :maxdepth: 2

   changelog

